include: package:flutter_lints/flutter.yaml

linter:
  rules:
    unnecessary_underscores: false
    use_build_context_synchronously: false

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    deprecated_member_use: ignore
