name: panenhub
description: "PanenHub - Aplikasi rantai pasok pertanian B2B"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  flutter_riverpod: ^2.6.1

  # Routing
  go_router: ^14.8.1

  # HTTP client
  dio: ^5.7.0

  # Secure session/token storage
  flutter_secure_storage: ^9.2.4

  # Local lightweight storage
  shared_preferences: ^2.3.5

  # Image loading and caching
  cached_network_image: ^3.4.1

  # Image picker for QC/dispute proof
  image_picker: ^1.1.2

  # Formatting
  intl: ^0.20.2

  # Loading placeholder
  shimmer: ^3.0.0

  # Google Fonts
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
