version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: panenhub_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: panenhub_db
    ports:
      - '5432:5432'
    volumes:
      - panenhub_pgdata:/var/lib/postgresql/data

volumes:
  panenhub_pgdata:
